### ISSUE TITLE
Use 14.04 (trusty) or older

### ISSUE THREAD

**Issue by probonopd** [knapsu/plex-media-player-appimage#1]
Interesting project. Please use 14.04 (trusty) or older as the basis for your AppImages; this way, they can run on older distributions, too. Thanks!

**Comment by knapsu** [comment]
Ubuntu Trusty has outdated packages for CMake and GCC. Resolved it by adding custom PPA-s, however when trying to run the AppImage on plain Ubuntu Trusty VM it will fail with the following error:

> /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./Plex_Media_Player_20170705_044db29_x86-64.AppImage)

Using new version of GCC (minimum GCC 4.9 is required to compile the code) will increase the dependency for `libstdc++` to version supported by it. Of course it will not be present on plain Trusty system.

**Comment by probonopd** [comment]
Please also see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6, specifically https://github.com/darealshinji/AppImageKit-checkrt/.

**Comment by knapsu** [comment]
Ubuntu 14.04 has reached its end of life. Closing as it will not be used as the base for the AppImage.

**Comment by probonopd** [comment]
Correct, 16.04 is now the new baseline.
