### ISSUE TITLE
error while loading shared libraries: libnsl.so.1

### ISSUE THREAD

**Issue by twhiston** [knapsu/plex-media-player-appimage#13]
With Fedora 28 (atomic workstation) I see the following error:
```
./Plex_Media_Player_2.11.0.867-f27f8d2a_x64.AppImage              
/tmp/.mount_Plex_MF3VTwG/usr/bin/plexmediaplayer: error while loading shared libraries: libnsl.so.1: cannot open shared object file: No such file or directory
```
However I have glibc installed

```
Inactive requests:
  glibc (already provided by glibc-2.27-15.fc28.x86_64)
```

**Comment by probonopd** [comment]
libnsl is not glibc. Do you have libnsl installed?

**Comment by knapsu** [comment]
@twhiston as a workaround run the following in a terminal:
`sudo dnf install libnsl`

This should install the library that is missing from AppImage bundle. Don't know why it's not included in the package.

**Comment by probonopd** [comment]
Indeed it is on https://github.com/AppImage/AppImages/blob/master/excludelist, seemingly because it was assumed to be part of glibc. Looks like this assumption was wrong or only correct for _some_ distributions?

**Comment by twhiston** [comment]
@probonopd It's in glibc in fedora 27 but not fedora 28

```
☿ podman run -it fedora:27 /bin/bash                                                                
[root@0ac2ed5ccbf5 /]# dnf provides libnsl.so.1
Fedora 27 - x86_64 - Updates                                                    992 kB/s |  24 MB     00:24    
Fedora 27 - x86_64                                                               19 MB/s |  58 MB     00:03    
Last metadata expiration check: 0:00:18 ago on Tue Jun  5 21:02:14 2018.
glibc-2.26-28.fc27.i686 : The GNU libc libraries
Repo        : updates
Matched from:
Provide    : libnsl.so.1

glibc-2.26-15.fc27.i686 : The GNU libc libraries
Repo        : fedora
Matched from:
Provide    : libnsl.so.1
```

```
podman run -it fedora:28 /bin/bash
[root@9251485ee3e2 /]# dnf provides libnsl.so.1
Fedora 28 - x86_64 - Updates                                                     11 MB/s |  14 MB     00:01    
Fedora 28 - x86_64                                                               29 MB/s |  60 MB     00:02    
Last metadata expiration check: 0:00:04 ago on Tue Jun  5 21:02:31 2018.
libnsl-2.27-15.fc28.i686 : Legacy support library for NIS
Repo        : updates
Matched from:
Provide    : libnsl.so.1

libnsl-2.27-8.fc28.i686 : Legacy support library for NIS
Repo        : fedora
Matched from:
Provide    : libnsl.so.1
```

**Comment by probonopd** [comment]
Uh oh. **UH OH!** This is screaming [Desktop Linux Platform Issues](https://github.com/AppImage/AppImageKit/wiki/Desktop-Linux-Platform-Issues)... distros can't even seem to agree what is part of glibc and what is not?!

**Comment by Conan-Kudo** [comment]
@probonopd It's built from the glibc source package, it's just subpackaged out because it's a deprecated library.

**Comment by probonopd** [comment]
> it's a deprecated library

Applications still might use it, so the Fedora/glibc team should not deprecate it. "Deprecate" in my opinion should be announced well ahead of time (a couple of years!) and only be executed once virtually all consumers have stopped consuming it.

Randomly "deprecating" stuff while consumers are still using it is just breaking it for users.

**Comment by Conan-Kudo** [comment]
That makes no sense. People won't stop using it unless people know to stop using it. Deprecation notices are quite literally the only way to make that work.

**Comment by probonopd** [comment]
_Notices_ yes. But not just doing it without notice well ahead of time...

**Comment by knapsu** [comment]
Fixed in 07cdb4ca39f67549d5c8962798c8fbffb98cc1e5

**Comment by probonopd** [comment]
So you are saying the only thing that pulls in NSL is the bundled `libnss*?` I'm interested to see whether deleting `libnss*` from the AppImage will have any ill consequences.

**Comment by knapsu** [comment]
It was committed on 8-th May (2 months ago). No one complained about it so far.

**Comment by probonopd** [comment]
So far I had assumed that libnss3.so should not be removed from the bundles, as this causes other issues, e.g., https://github.com/probonopd/linuxdeployqt/issues/35#issuecomment-256213517.

**Comment by pnaraya4** [comment]
installing packages libX11.i686 and libnsl.i686 resolved my issue

**Comment by probonopd** [comment]
libnsl _should_ be bundled with the application. _Would_ this resolve the issue?

**Comment by msashish** [comment]
If it helps: I was using RHEL8 base image with python 3.8 and Oracle instant client which gave me the same error when I attempted to access using cx_Oracle. I read that libnsl.so.1 is removed from glibc package and there is a libnsl.so.2 that comes with RHEL8 base image.
Symlink-ing libnsl.so.1 worked for me:
ln -s /usr/lib64/libnsl.so.2 /usr/lib64/libnsl.so.1

**Comment by husamazma** [comment]
please try: sudo yum install libnsl

it automatically created a ln : /usr/lib64/libnsl.so.1 -> libnsl-2.28.so
