### ISSUE TITLE
libpango-1.0.so.0 undefined symbol: fribidi_get_par_embedding_levels_ex

### ISSUE THREAD

**Issue by erenfro** [knapsu/plex-media-player-appimage#14]
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
Logging to /home/psi-jack/.local/share/plexmediaplayer/logs/plexmediaplayer.log
Logging to /home/psi-jack/.local/share/plexmediaplayer/logs/pmphelper.log
/usr/bin/google-chrome-stable: symbol lookup error: /usr/lib/libpango-1.0.so.0: undefined symbol: fribidi_get_par_embedding_levels_ex

**Comment by erenfro** [comment]
This is in current stable and daily 20180616 build. And on Solus 3 current and up-to-date. Stable build had further issues with XPCOM, but have been seemed to be fixed in current daily.

**Comment by knapsu** [comment]
This log shows when you start the AppImage or after clicking the "sign in" button when application window is displayed?

**Comment by ibrahimmkhalid** [comment]
after clicking "sign in"

this shows when i click it
XPCOMGlueLoad error for file /usr/lib/firefox/libmozgtk.so:
/usr/lib/libpango-1.0.so.0: undefined symbol: fribidi_get_par_embedding_levels_ex
Couldn't load XPCOM.

tested on latest stable and daily(20180727) builds

**Comment by probonopd** [comment]
Not bundling `libfribidi.so.0` may solve this, but can we assume `libfribidi.so.0` to be "there" on every target system (distribution)?

**Comment by ibrahimmkhalid** [comment]
But isn't that the whole point of appimages? You don't need to install package `xyz` for the program to work, it just works(TM). 

Is there any workaround to this?

**Comment by probonopd** [comment]
Right. We need to check whether `libfribidi.so.0` can be taken for granted to be there on each target system. If yes, we don't need to bundle a private copy. If not, we do need to bundle it.

**Comment by knapsu** [comment]
`libfribidi.so.0` removed from AppImage.
