### ISSUE TITLE
AppImage won't start on Manjaro Linux 17.1.11

### ISSUE THREAD

**Issue by tyjuji** [knapsu/plex-media-player-appimage#15]
Executing the AppImage causes it to ask about desktop integration and then abort immediately and log to plexmediaplayer.log once I've finished the dialogue.
I've had similar issues with other AppImages, but they report missing dependencies that I can install, while the PMP image does not.
Extracting the AppImage and running plexmediaplayer.wrapper directly works just fine.

AppImage Version = Plex_Media_Player_2.14.1.880-301a4b6c_x64
All versions, that I've tried, have failed. To make sure, I've checked the lastest daily as well as 2.15 and they have the same issue.

Kernel Version = 4.17.9-1-MANJARO
Qt Version = 5.11.1
KDE Plasma Version = 5.13.3

plexmediaplayer.log: https://pastebin.com/xTXYZWMr

**Comment by bipox** [comment]
Same on Manjaro Xfce

**Comment by knapsu** [comment]
Hi. Sorry for late response. Been busy with other work.

Will get Manjaro Linux and check this.

@tyjuji nothing caught my eye when looking at the log. Can you point me to other AppImages that shows the missing dependencies? It would be good to add this functionality to PMP AppImage.

**Comment by probonopd** [comment]
If this AppImage is still using the desktop integration bash script, then maybe it's worth considering to remove it. Tools like the optional `appimaged` daemon or AppImageLauncher can be used for desktop integration if so desired.

**Comment by tyjuji** [comment]
@knapsu Take for example the Subsurface image from appimage.org
It reports some QT5 plugins that are missing. I'm pretty sure there were other dependencies as well, but I must have installed those already. 
Console output: https://pastebin.com/X3CkCeGc

**Comment by knapsu** [comment]
Tested on **Manjaro 18.0.4** and [latest daily build](https://knapsu.eu/data/plex/Plex_Media_Player_20190515_36e9306d_x64.AppImage) works without problems after blacklisting `libxcb-dri2.so` and `libxcb-dri3.so` libraries that were causing crashes.
The release build 2.33.1 does not have those libraries excluded so it will not work.
