### ISSUE TITLE
Screen tearing on 4k monitor, kubuntu 18.10

### ISSUE THREAD

**Issue by syco** [knapsu/plex-media-player-appimage#21]
Hi,
I'm having this issue with screen tearing on 2 different computers, with 2 different monitors, both 4k.
It happens especially in the menus, during playback luckily it is rare to happen (attached 3 screenshot).
Did anyone else have this issue, or knows how to solve it?
![screenshot_20181228_122209](https://user-images.githubusercontent.com/54575/50515318-ba1a3880-0a9b-11e9-876f-047566a040af.png)
![screenshot_20181228_122250](https://user-images.githubusercontent.com/54575/50515320-ba1a3880-0a9b-11e9-9814-32d9405ef363.png)
![screenshot_20181228_122301](https://user-images.githubusercontent.com/54575/50515321-ba1a3880-0a9b-11e9-8d4b-e71bb719d1c9.png)

my graphic cards are:
```bash
PC1: 00:02.0 VGA compatible controller: Intel Corporation HD Graphics 620 (rev 02)
PC2: 00:02.0 VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09)
```

Video driver:
i915 for both
```bash
ii  i965-va-driver:amd64                            2.2.0-0ubuntu1                                  amd64        VAAPI driver for Intel G45 & HD Graphics family
ii  xserver-xorg-video-intel                        2:2.99.917+git20171229-1ubuntu1                 amd64        X.Org X server -- Intel i8xx, i9xx display driver
```

Please let me know if you need any other info, or want me to test anything.
Thanks

**Comment by knapsu** [comment]
Can you check if [this](https://knapsu.eu/data/plex/Plex_Media_Player_20190122_c539e285_x64_novaapi.AppImage) works for you?

Intel VA-API is disabled in this build. It might be necessary to have `vdpau-va-driver` package installed to have HW acceleration working. Please tell me if screen tearing is stil there (1) and if hardware decoding is working (2).

**Comment by syco** [comment]
Hi, I tried this version you linked, below the va/intel packages I've installed, but it didn't solve the problem.
```bash
$ dpkg -l|grep va-driver
ii  i965-va-driver:amd64                          2.2.0-0ubuntu1                              amd64        VAAPI driver for Intel G45 & HD Graphics family
ii  vdpau-va-driver:amd64                         0.7.4-7                                     amd64        VDPAU-based backend for VA API
$ dpkg -l|grep intel
ii  intel-microcode                               3.20180807a.1                               amd64        Processor microcode firmware for Intel CPUs
ii  libdrm-intel1:amd64                           2.4.95-1                                    amd64        Userspace interface to intel-specific kernel DRM services -- runtime
ii  xserver-xorg-video-intel                      2:2.99.917+git20171229-1ubuntu1             amd64        X.Org X server -- Intel i8xx, i9xx display driver
$ ./Plex_Media_Player_20190122_c539e285_x64_novaapi.AppImage 
libpng warning: iCCP: known incorrect sRGB profile
Logging to /home/syco/.local/share/plexmediaplayer/logs/plexmediaplayer.log
Logging to /home/syco/.local/share/plexmediaplayer/logs/pmphelper.log
[0130/232535.377697:WARNING:stack_trace_posix.cc(699)] Failed to open file: /home/syco/#3672081 (deleted)
  Error: No such file or directory
Cannot load libcuda.so.1
```

**Comment by knapsu** [comment]
It appears this is a PMP internal libraries problem that I can't handle on packaging side.

**Comment by knapsu** [comment]
Hi @syco. Do you still suffer from screen tearing issues with the recent PMP versions?

**Comment by syco** [comment]
Hi, it's working probably since a few versions. I just updated to the latest and it's still works.

**Comment by syco** [comment]
Also, I've updated to 19.04 in the meantime, so it's not 18.10 anymore.
Thanks..

**Comment by knapsu** [comment]
That's great to hear.
