### ISSUE TITLE
m3u streaming, audio but no video

### ISSUE THREAD

**Issue by syco** [knapsu/plex-media-player-appimage#22]
Hi,
I'm using a plugin to grab m3u lists from an Italian website and provide them to plex, my issue is that the streaming from this website works fine in windows and in android, but it doesn't work on ubuntu. I tried both the appimage and the flatpak.
The issue is that I get the audio, but the video doesn't show.
Could it be a codec issue? Do you have any advice, or test I can do?
Thanks

**Comment by probonopd** [comment]
Please run from the command line and watch for any error messages.

**Comment by syco** [comment]
Hi, here's the output of the appimage and the log file created
```bash
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so has no function __vaDriverInit_0_32
libva info: va_openDriver() returns -1
Logging to /home/syco/.local/share/plexmediaplayer/logs/plexmediaplayer.log
```

[plexmediaplayer.log](https://github.com/knapsu/plex-media-player-appimage/files/2775646/plexmediaplayer.log)

**Comment by probonopd** [comment]
https://github.com/intel/media-driver/issues/235

**Comment by syco** [comment]
Thanks, but I don't think the issue is the intel driver,
Attached there's a screencast and here's what I'm doing in it:
I open plex in standard view, navigate to the streaming plugin and start streaming live, streaming works fine.
I close the streaming, exit the plugin and go back to the home, change the layout to TV, and navigate back to the same plugin, and start the same live video.
Now I still ear the audio, but I don't see any video.
Funny thing, when I resize the window you can see that the video is there, but it's sort hiding behind the blurred background layer.

[Screencast 2019-01-21 15:08:16.zip](https://github.com/knapsu/plex-media-player-appimage/files/2779441/Screencast.2019-01-21.15.08.16.zip)

**Comment by knapsu** [comment]
Hi @syco. This is not a problem with AppImage or Flatpak packaging but with ffmpeg or mpv that is used by Plex Media Player. Most likely something extra must be enabled during compilation time.

@probonopd the issue you are referencing is about host system VA-API video driver being in incompatible version with the `libva*.so` that is bundled with AppImage. This is a different issue than the one reported.

With your instructions how to reproduce this I can give it a try and experiment. Thanks for those.

**Comment by knapsu** [comment]
@syco just checked your video, installed your LA7 plugin and done as instructed. I can confirm the problem. I've also run other Plex plugins and didn't experience such issue, for example [South Park](https://github.com/plexinc-plugins/South-Park.bundle) plugin.

I would suggest to compare the code with those official Plex plugins that do have live streams as there might be something needed to make it run properly with TV UI.

**Comment by knapsu** [comment]
Tested it with PMP 2.25.0 + ffmpeg 4.0.3 + mpv 0.29.1 + Qt 5.11.3 and the problem still exists.

This is a bug in Plex Media Player UI for TV layout under Linux. You should report it [here](https://github.com/plexinc/plex-media-player).

Sorry but I can't help any further with this one.

**Comment by syco** [comment]
Thanks for trying the plugin, it was very helpful to know it wasn't only me.
The official plugins unfortunately rely on the Service.bundle and I can't use that.
But I went digging into its code and found a combination of VideoClipObject/MediaObject that works for me too.
I leave a piece of code here for whoever might find it useful:
url in this case is a m3u8 link
```python
@route('/video/la7/show', include_container = bool)
def Show(url, title, include_container = False, **kwargs):
  vco = VideoClipObject(
    url = url,
    title = title,
    items = [
      MediaObject(
        parts = [
          PartObject(
            key = HTTPLiveStreamURL(Callback(Play, url = url))
          )
        ],
      )
    ]
  )
  if include_container:
    return ObjectContainer(objects = [vco])
  else:
    return vco

@indirect
@route('/video/la7/play.m3u8')
def Play(url, **kwargs):
  Log(' --> Final stream url: %s' % (url))
  return IndirectResponse(VideoClipObject, key = url)
```

I'll enjoy streaming while I still can, plex is axing the whole plugin system apparently.
