### ISSUE TITLE
[Feature Request] Support for Media Keys

### ISSUE THREAD

**Issue by hasezoey** [knapsu/plex-media-player-appimage#23]
Linux Mint 19.1
Plex AppImage Version `20190130_542ba3ed_x64`

i would like to see support for Media Keys, the Hardware ones, that are on much keyboards (like how they work in Rhythmbox)

**Comment by knapsu** [comment]
Hi @hasezoey. This repository is about AppImage packaging for Linux.
For feature requests in Plex app please go to https://github.com/plexinc/plex-media-player/issues
Thanks.

**Comment by hasezoey** [comment]
I thought i ask here, because this is the only linux "port", and because linux player is not officially supported (and i dont know if the windows / OSX version have this already)
