### ISSUE TITLE
Plex Media Player on Intel NUC (Ubuntu 19) won’t play when passthrough enabled 

### ISSUE THREAD

**Issue by craigmdennis** [knapsu/plex-media-player-appimage#26]
```
Server Version#: Version 1.16.3.1402
Server OS: Ubuntu 19
Player Version#: 3.104.1
player (for Ubuntu) Downloaded from: https://github.com/knapsu/plex-media-player-appimage
Equipment Connection: NUC -> Onkyo 686 -> LG B6 OLED (all using HDMI 2.1 cables)
```

I have everything set up and can see passthrough for all the audio codecs that show up as my received supports them all.

![image](https://user-images.githubusercontent.com/725067/61727518-6c348d00-ad6b-11e9-91bc-2544dda99001.png)

Only AC3 files will play, none of the TrueHD files. If I enable passthrough then not even the AC3 files play.

I can see from the server that the files are ‘playing’ and are direct playing but even here it does not show the thumbnail preview changing.

![image](https://user-images.githubusercontent.com/725067/61727536-748cc800-ad6b-11e9-9944-fa679fb6e89b.png)

Originally posted:
https://forums.plex.tv/t/plex-media-player-on-intel-nuc-ubuntu-19-wont-play-when-passthrough-enabled/436572

**Comment by knapsu** [comment]
Hi. Due to the nature of the problem I was unable to work on it (don't have access to Intel hardware). Sorry.

As it is now few years old I will close is as it references a very old version PMP.
Feel free to create a new issue if the problem still occurs with the latest PMP version.
