### ISSUE TITLE
Plex media player on lxc proxmox

### ISSUE THREAD

**Issue by dim020782** [knapsu/plex-media-player-appimage#27]
Hi,

I want to install Plex media Player in a container lxc gui on proxmox

I gave the GPU, keyboard, mouse and sound access to the container following this link: https://blog.konpat.me/dev/2019/03/11/setting-up-lxc-for-intel-gpu-proxmox.html
and apart from the sound that I could not try, I have the image on my tv via the output hdmi
I did the test by installing this template: https://sourceforge.net/projects/ubuntu-business-desktop-lxc/

I created a container with the following config:
arch: amd64
cores: 2
features: fuse=1
hostname: plex
memory: 2048
net0: name=eth0,bridge=vmbr0,firewall=1,gw=192.168.1.1,hwaddr=E2:FA:71:F0:CF:EC,ip=192.168.1.130/24,type=veth
ostype: debian
rootfs: local-lvm:vm-130-disk-0,size=8G
swap: 512
lxc.cgroup.devices.allow: c 226:0 rwm
lxc.cgroup.devices.allow: c 226:128 rwm
lxc.cgroup.devices.allow: c 4:7 rwm
lxc.cgroup.devices.allow: c 29:0 rwm
lxc.mount.entry: /dev/dri/card0 dev/dri/card0 none bind,optional,create=file
lxc.mount.entry: /dev/dri/renderD128 dev/dri/renderD128 none bind,optional,create=file
lxc.mount.entry: /dev/tty7 dev/tty7 none bind,optional,create=file
lxc.mount.entry: /dev/fb0 dev/fb0 none bind,optional,create=file
lxc.cgroup.devices.allow: c 13:* rwm
lxc.mount.entry: /dev/input dev/input none bind,optional,create=dir
lxc.cgroup.devices.allow: c 116:* rwm
lxc.mount.entry: /dev/snd dev/snd none bind,optional,create=dir

I downloaded plex, made executable, but I can not install it
wget https://knapsu.eu/data/plex/Plex_Media_Player_2.42.0.1013-712b8c6f_x64.AppImage
chmod a+x Plex_Media_Player_2.42.0.1013-712b8c6f_x64.AppImage
./Plex_Media_Player_2.42.0.1013-712b8c6f_x64.AppImage

I have the following error message
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: xcb.

I installed missing packages, including gnome-core but nothing done

**Comment by knapsu** [comment]
Hi. Due to the nature of the problem I was unable to work on it (don't use Proxmox). Sorry.

As it is now few years old I will close is as it references a very old version PMP.
Feel free to create a new issue if the problem still occurs with the latest PMP version.
