### ISSUE TITLE
Appimage nor Flatpak will run

### ISSUE THREAD

**Issue by 2635599** [knapsu/plex-media-player-appimage#28]
i have trued both the appimage and flatpak for plex media player and neither will run. appimage sits on the login screen and when you click signin it does nothing. the frlatpak looks like it installed fine via knosole but can't find it anywhere. i just installed kubuntu 19.10 64 bit yesterday, and i have plex media server up and running without any issues. please any suggestions. thanks

**Comment by knapsu** [comment]
In FAQ section on https://knapsu.eu/plex/ there is info about "Sign In" button not working. Please take a look at this workaround (use fullscreen mode).

Flatpak should cause the system to create Menu entry on its own. Don't have an idea why it could fail.

**Comment by 2635599** [comment]
ok that did the trick. stuck it's tongue out at me the last time i tried that, but this time i signed into the server first then went to the link page. thanks a lot.
