### ISSUE TITLE
[NOBUG] Thank you for your awesome work!

### ISSUE THREAD

**Issue by MikeeI** [knapsu/plex-media-player-appimage#29]
I searched for the best plex client and i considered NVIDIA Shield and so on, but due to your **awesome** work i can just use my a raspberry pi or another pc.

This is so easy to install and use.

Just a thank you. :-) 

![THX](https://media3.giphy.com/media/5wWf7GWELURDhqXtGRW/200.gif)

**Comment by knapsu** [comment]
It makes me really happy that you find my work useful :smiley:  
Take care!
