### ISSUE TITLE
Also host on github

### ISSUE THREAD

**Issue by dirtycajunrice** [knapsu/plex-media-player-appimage#30]
Hosting the images on github allows appimagehub to point to them. knapsu.eu downloads extremely slowly for me which also is unwanted. Thoughts?

**Comment by probonopd** [comment]
Would appreciate GitHub Releases having AppImages. :+1:

**Comment by knapsu** [comment]
Hi. Few people reported that my website hosting is slow so AppImage packages are being mirrored on GitHub for some time now. Forgot to close this ticket when it was done.
