### ISSUE TITLE
PMP crashes

### ISSUE THREAD

**Issue by DaveHarton** [knapsu/plex-media-player-appimage#33]
Ubuntu 20.04
PMP Version 4.29.2
PMP randomly crashes:
dave@dave-desktop:~$ "/home/dave/Downloads/Plex_Media_Player_20200618_05368698_x64.AppImage" %U
libpng warning: iCCP: known incorrect sRGB profile
Logging to /home/dave/.local/share/plexmediaplayer/logs/plexmediaplayer.log
Logging to /home/dave/.local/share/plexmediaplayer/logs/pmphelper.log
../../3rdparty/chromium/sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230

**Comment by knapsu** [comment]
This seems to be a problem with Qt 5.12.6 that is used now.
The fix was backported to Qt 5.12.8
https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/292345

Unfortunately:
- Qt 5.12.7+ does not build successfully on Bionic which forces me to use Qt 5.12.6
- Qt 5.9 is not available in Bionic

The only way I see is to downgrade Linux base back to Xernial. This will remove all potential gains of newer Linux base to which I switched recently.

Will give this a thought.

**Comment by DaveHarton** [comment]
Hi Krzysztof,

Thanks for the reply. I am sure you will come up with a fix :)

Cheers,
Dave

**Comment by knapsu** [comment]
@DaveHarton 
Please check if this one works for you
https://knapsu.eu/data/plex/Plex_Media_Player_20200707-05368698-qt59_x64.AppImage

**Comment by DaveHarton** [comment]
So far so good... It normally happens when browsing the DVR. So far no
crashes :) I'll keep on it for a bit

**Comment by DaveHarton** [comment]
Yep - seems to be all good now. Thanks so much

**Comment by knapsu** [comment]
OK, pushing the changes so next AppImage release will have it. Thanks for informing me about this.

Funny as for Flatpak the Qt 5.9 ins unstable and Qt 5.12 seems good. The exact opposite for AppImage.

**Comment by DaveHarton** [comment]
And now with Ubuntu 20.10 it has reverted! Opens and closes again. Guess we
need the original release!

From terminal:
sh  Plex_Media_Player_20201004-05368698_x64.AppImage
Plex_Media_Player_20201004-05368698_x64.AppImage: 1: �: not found
Plex_Media_Player_20201004-05368698_x64.AppImage: 2: }�P7pys�H��_f��h: not
found
Plex_Media_Player_20201004-05368698_x64.AppImage: 1: �b�@@: not found
Plex_Media_Player_20201004-05368698_x64.AppImage: 1: ELFAI: not found
Plex_Media_Player_20201004-05368698_x64.AppImage: 19: Syntax error:
Unterminated quoted string

**Comment by strykenKN** [comment]
Plex Media Player crashes under Ubuntu 20.10

I installed Ubuntu 20.10 today and I will not downgrade! And Plex crashes completely on startup, no matter what I do, it won't start! And why is the topic closed, if the problem has not been solved ?
