### ISSUE TITLE
Add support for L4T Nintendo Switch Ubuntu 18 (Tegra X1)

### ISSUE THREAD

**Issue by VegethB** [knapsu/plex-media-player-appimage#34]
I know it will seem an absurd request, I would like to consider the possibility of installing and starting the PMP also on L4T. I tried appimage but it says: `cannot execute binary file: exec format error.`
Flatpak instead installs but then if you do `flatpak list` nothing comes out of the list and obviously I can not find anywhere app.
It would be nice if it also supported Api for the X1 GPU.

Nvidia Tegra X1 ArmV8 x64.

**Comment by probonopd** [comment]
The low-level AppImage tools are available for armhf (32-bit ARM) and aarch64 (64-bit ARM):  https://github.com/AppImage/AppImageKit/releases

**Comment by knapsu** [comment]
@zFerry98 it is impossible because:
- Plex Media Player requires x86/x86_64 processor and you have ARM processor.
- [linuxdeployqt ](https://github.com/probonopd/linuxdeployqt) tool that is used for building the package is not available for architectures other than `x86_64`.

**Comment by probonopd** [comment]
> linuxdeployqt tool that is used for building the package is not available for architectures other than x86_64

It's being worked on: https://github.com/probonopd/linuxdeployqt/pull/447

**Comment by VegethB** [comment]
👍🤷‍♂️
