### ISSUE TITLE
Not starting Up

### ISSUE THREAD

**Issue by ghost** [knapsu/plex-media-player-appimage#36]
I have install plex Appimage on fresh clear Linux and when I click on plex nothing happens any suggestions

**Comment by LLinoor** [comment]
Yes, indeed the appimage does not work on the latest major versions of Linux distributions. I'm on Ubuntu 20.10 and I confirm that it doesn't work :(

**Comment by SemiCroustii** [comment]
Doesn't start on PopOS after upgrade from 20.04 to 20.10

**Comment by psxpaul** [comment]
It looks like this is similar to #11 , but for libvulkan.so.1. I did the following and it fixed the issue for me:

```
./Plex_Media_Player_2.58.0.1076-38e019da_x64.AppImage --appimage-extract
cd squashfs-root
rm usr/lib/libvulkan.so.1
../appimagetool-x86_64.AppImage .
```
The appimagetool is from [here](https://github.com/AppImage/AppImageKit/releases). It will spit out a new file `squashfs-root/Plex_Media_Player-x86_64.AppImage` that starts without errors for me.

**Comment by SemiCroustii** [comment]
> It looks like this is similar to #11 , but for libvulkan.so.1. I did the following and it fixed the issue for me:
> 
> ```
> ./Plex_Media_Player_2.58.0.1076-38e019da_x64.AppImage --appimage-extract
> cd squashfs-root
> rm usr/lib/libvulkan.so.1
> ../appimagetool-x86_64.AppImage .
> ```
> 
> The appimagetool is from [here](https://github.com/AppImage/AppImageKit/releases). It will spit out a new file `squashfs-root/Plex_Media_Player-x86_64.AppImage` that starts without errors for me.

It worked ! thanks

**Comment by knapsu** [comment]
Hi. Sorry for late reply. I am very busy lately with other projects.

Indeed the problem is with the `libvulkan.so` library. Thanks @hell0-Wor1d for providing a fix when I was not around.

I can confirm the latest daily build works. Will repackage the `2.58.0.1076` version.

**Comment by knapsu** [comment]
Repackaged. Download links updated.
