### ISSUE TITLE
PMP crashes under Ubuntu 20.10 !!!

### ISSUE THREAD

**Issue by strykenKN** [knapsu/plex-media-player-appimage#37]
I installed Ubuntu 20.10 today and I will not downgrade! And Plex crashes completely on startup, no matter what I do, it won't start!

**Comment by LLinoor** [comment]
Hi, 
**If you want to make your own .appimage :**
I advise you to download the **December "Daily Build"** [(_here_)](https://knapsu.eu/data/plex/Plex_Media_Player_20201201-05368698_x64.AppImage) and to follow the instructions that may have already been given in a **previous issue** (#36)

> `./Plex_Media_Player_2.58.0.1076-38e019da_x64.AppImage --appimage-extract`
> `cd squashfs-root`
> `rm usr/lib/libvulkan.so.1`
> `../appimagetool-x86_64.AppImage .`

(You can download AppImageTool here: https://github.com/AppImage/AppImageKit/releases)

**If you want a .appimage already modified :**
(Created and tested with Ubuntu 20.10)

Link : https://drive.google.com/file/d/1Yrs8tXa3teRPtNt9YNjUe2_SWcyTox_d/view?usp=sharing

**Comment by knapsu** [comment]
Hi. Sorry for late reply. I am very busy lately with other projects.

Indeed the problem is with the `libvulkan.so` library.

I can confirm the latest daily build works. Will repackage the `2.58.0.1076` version.

**Comment by knapsu** [comment]
Repackaged. Download links updated.
