### ISSUE TITLE
Downloading doesn't work

### ISSUE THREAD

**Issue by JVT038** [knapsu/plex-media-player-appimage#38]
If I click on 'Download', it should start downloading the selected movie / episode, but nothing happens.
could you fix this? 

I use v2.58.0.1076-38e019da, and I run PoP! OS 21.04

**Comment by knapsu** [comment]
Hi. Downloading files indeed does not work with AppImage nor Flatpak packages. Unfortunately I don't think that I can do anything with this on packaging side. 
This should be reported to the Plex developers instead.
