### ISSUE TITLE
Shutdown option

### ISSUE THREAD

**Issue by ghost** [knapsu/plex-media-player-appimage#5]
Hello!

thanks a lot for your hard work, it's really appreciated. I was wondering if there is a way to get the shutdown option when closing? I currently have cancel and Relaunch (which is really just Quit).

thanks & happy new year

**Comment by knapsu** [comment]
Hi there. This is something that only Plex developers can do. I only take care of the AppImage package. Please create a feature request in https://github.com/plexinc/plex-media-player
