### ISSUE TITLE
.desktop shortcut not consistent with running application

### ISSUE THREAD

**Issue by Snowman3456** [knapsu/plex-media-player-appimage#7]
![plex_issue](https://user-images.githubusercontent.com/4528283/35950366-2dbfe5b6-0c44-11e8-8683-1870115563ce.png)

Plex Media Player was launched with the shortcut above but the running application doesn't register as that application.

System is Ubuntu 17.10

**Comment by probonopd** [comment]
Please add the correct `StartupWMClass` key in the .desktop file to solve the problem.

Reference:
https://github.com/AppImage/AppImageKit/issues/260

**Comment by knapsu** [comment]
Thanks @probonopd . Will do!
