### ISSUE TITLE
Get the AppImage published by https://www.plex.tv/

### ISSUE THREAD

**Issue by probonopd** [knapsu/plex-media-player-appimage#8]
Do you plan to get the AppImage officially published and supported (or at least officially endorsed, i.e., linked on their download page) by the upstream authors at https://www.plex.tv/?

**Comment by knapsu** [comment]
Yes, talked with Plex already, however they do not want to publish anything other than packages built directly by them. They liked my work but needed time to see if they can adapt their build system. Plex Media Player development for Linux got completely quiet last few months so maybe they lost interest in Linux version.

My way of sharing info about AppImage packages is done through official Linux section on Plex Forums:
https://forums.plex.tv/discussion/278570/plex-media-player-packages-for-linux/p1

**Comment by probonopd** [comment]
> maybe they lost interest in Linux version

That'd be a shame. Anyway, keep up your great work!
