### ISSUE TITLE
Unable to run any of the appimage(s) - v1 & 2 - available for PMP

### ISSUE THREAD

**Issue by antoan** [knapsu/plex-media-player-appimage#9]
Ubuntu 14.04 LTS - 64bit

$./Plex_Media_Player_2.2.1.758-5dad2d62_x86-64.AppImage 

/tmp/.mount_Plex_MVMkRR7/usr/bin/plexmediaplayer: /lib/x86_64-linux-gnu/libgpg-error.so.0: no version information available (required by /tmp/.mount_Plex_MVMkRR7/usr/lib/libgcrypt.so.20)
/tmp/.mount_Plex_MVMkRR7/usr/bin/plexmediaplayer: relocation error: /tmp/.mount_Plex_MVMkRR7/usr/lib/libboost_system.so.1.58.0: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

Wondering what this might be about? The output is the same when trying v1.3.12.755.

**Comment by knapsu** [comment]
Hi @antoan. Unfortunately Ubuntu 16.04 (Xenial) or newer is required.
Please see #1 for more detailed explanation why it can not work with Ubuntu 14.04 (Trusty).
